# Using Jupyter Notebooks
:label:`sec_jupyter`


This section describes how to edit and run the code
in each section of this book
using the Jupyter Notebook. Make sure you have
installed Jupyter and downloaded the
code as described in
:ref:`chap_installation`.
If you want to know more about Jupyter see the excellent tutorial in
their [documentation](https://jupyter.readthedocs.io/en/latest/).


## Editing and Running the Code Locally

Suppose that the local path of the book's code is `xx/yy/d2l-en/`. Use the shell to change the directory to this path (`cd xx/yy/d2l-en`) and run the command `jupyter notebook`. If your browser does not do this automatically, open http://localhost:8888 and you will see the interface of Jupyter and all the folders containing the code of the book, as shown in :numref:`fig_jupyter00`.

![The folders containing the code of this book.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter00.png?raw=1)
:width:`600px`
:label:`fig_jupyter00`


You can access the notebook files by clicking on the folder displayed on the webpage.
They usually have the suffix ".ipynb".
For the sake of brevity, we create a temporary "test.ipynb" file.
The content displayed after you click it is
shown in :numref:`fig_jupyter01`.
This notebook includes a markdown cell and a code cell. The content in the markdown cell includes "This Is a Title" and "This is text.".
The code cell contains two lines of Python code.

![Markdown and code cells in the "text.ipynb" file.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter01.png?raw=1)
:width:`600px`
:label:`fig_jupyter01`


Double click on the markdown cell to enter edit mode.
Add a new text string "Hello world." at the end of the cell, as shown in :numref:`fig_jupyter02`.

![Edit the markdown cell.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter02.png?raw=1)
:width:`600px`
:label:`fig_jupyter02`


As demonstrated in :numref:`fig_jupyter03`,
click "Cell" $\rightarrow$ "Run Cells" in the menu bar to run the edited cell.

![Run the cell.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter03.png?raw=1)
:width:`600px`
:label:`fig_jupyter03`

After running, the markdown cell is shown in :numref:`fig_jupyter04`.

![The markdown cell after running.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter04.png?raw=1)
:width:`600px`
:label:`fig_jupyter04`


Next, click on the code cell. Multiply the elements by 2 after the last line of code, as shown in :numref:`fig_jupyter05`.

![Edit the code cell.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter05.png?raw=1)
:width:`600px`
:label:`fig_jupyter05`


You can also run the cell with a shortcut ("Ctrl + Enter" by default) and obtain the output result from :numref:`fig_jupyter06`.

![Run the code cell to obtain the output.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter06.png?raw=1)
:width:`600px`
:label:`fig_jupyter06`


When a notebook contains more cells, we can click "Kernel" $\rightarrow$ "Restart & Run All" in the menu bar to run all the cells in the entire notebook. By clicking "Help" $\rightarrow$ "Edit Keyboard Shortcuts" in the menu bar, you can edit the shortcuts according to your preferences.

## Advanced Options

Beyond local editing two things are quite important: editing the notebooks in the markdown format and running Jupyter remotely.
The latter matters when we want to run the code on a faster server.
The former matters since Jupyter's native ipynb format stores a lot of auxiliary data that is
irrelevant to the content,
mostly related to how and where the code is run.
This is confusing for Git, making
reviewing contributions very difficult.
Fortunately there is an alternative---native editing in the markdown format.

### Markdown Files in Jupyter

If you wish to contribute to the content of this book, you need to modify the
source file (md file, not ipynb file) on GitHub.
Using the notedown plugin we
can modify notebooks in the md format directly in Jupyter.


First, install the notedown plugin, run the Jupyter Notebook, and load the plugin:

```
pip install d2l-notedown  # You may need to uninstall the original notedown.
jupyter notebook --NotebookApp.contents_manager_class='notedown.NotedownContentsManager'
```

You may also turn on the notedown plugin by default whenever you run the Jupyter Notebook.
First, generate a Jupyter Notebook configuration file (if it has already been generated, you can skip this step).

```
jupyter notebook --generate-config
```

Then, add the following line to the end of the Jupyter Notebook configuration file (for Linux or macOS, usually in the path `~/.jupyter/jupyter_notebook_config.py`):

```
c.NotebookApp.contents_manager_class = 'notedown.NotedownContentsManager'
```

After that, you only need to run the `jupyter notebook` command to turn on the notedown plugin by default.

### Running Jupyter Notebooks on a Remote Server

Sometimes, you may want to run Jupyter notebooks on a remote server and access it through a browser on your local computer. If Linux or macOS is installed on your local machine (Windows can also support this function through third-party software such as PuTTY), you can use port forwarding:

```
ssh myserver -L 8888:localhost:8888
```

The above string `myserver` is the address of the remote server.
Then we can use http://localhost:8888 to access the remote server `myserver` that runs Jupyter notebooks. We will detail on how to run Jupyter notebooks on AWS instances
later in this appendix.

### Timing

We can use the `ExecuteTime` plugin to time the execution of each code cell in Jupyter notebooks.
Use the following commands to install the plugin:

```
pip install jupyter_contrib_nbextensions
jupyter contrib nbextension install --user
jupyter nbextension enable execute_time/ExecuteTime
```

## Summary

* Using the Jupyter Notebook tool, we can edit, run, and contribute to each section of the book.
* We can run Jupyter notebooks on remote servers using port forwarding.


## Exercises

1. Edit and run the code in this book with the Jupyter Notebook on your local machine.
1. Edit and run the code in this book with the Jupyter Notebook *remotely* via port forwarding.
1. Compare the running time of the operations $\mathbf{A}^\top \mathbf{B}$ and $\mathbf{A} \mathbf{B}$ for two square matrices in $\mathbb{R}^{1024 \times 1024}$. Which one is faster?


[Discussions](https://discuss.d2l.ai/t/421)

In [4]:
from google.colab import files
uploaded = files.upload()

Saving patients.csv to patients.csv
Saving services_weekly.csv to services_weekly.csv
Saving staff.csv to staff.csv
Saving staff_schedule.csv to staff_schedule.csv

In [5]:
import pandas as pd
import numpy as np

In [6]:
patients = pd.read_csv("patients.csv")
services = pd.read_csv("services_weekly.csv")
staff = pd.read_csv("staff.csv")
schedule = pd.read_csv("staff_schedule.csv")

In [7]:
patients.head()

,patient_id,name,age,arrival_date,departure_date,service,satisfaction
0,PAT-09484753,Richard Rodriguez,24,2025-03-16,2025-03-22,surgery,61
1,PAT-f0644084,Shannon Walker,6,2025-12-13,2025-12-14,surgery,83
2,PAT-ac6162e4,Julia Torres,24,2025-06-29,2025-07-05,general_medicine,83
3,PAT-3dda2bb5,Crystal Johnson,32,2025-10-12,2025-10-23,emergency,81
4,PAT-08591375,Garrett Lin,25,2025-02-18,2025-02-25,ICU,76

In [8]:
services.head()

,week,month,service,available_beds,patients_request,patients_admitted,patients_refused,patient_satisfaction,staff_morale,event
0,1,1,emergency,32,76,32,44,67,70,none
1,1,1,surgery,45,130,45,85,83,78,flu
2,1,1,general_medicine,37,201,37,164,97,43,flu
3,1,1,ICU,22,31,22,9,84,91,flu
4,2,1,emergency,28,169,28,141,75,64,none

In [9]:
schedule.head()

   week      staff_id    staff_name    role    service  present
0     1  STF-b77cdc60  Allison Hill  doctor  emergency        1
1     2  STF-b77cdc60  Allison Hill  doctor  emergency        1
2     3  STF-b77cdc60  Allison Hill  doctor  emergency        0
3     4  STF-b77cdc60  Allison Hill  doctor  emergency        1
4     5  STF-b77cdc60  Allison Hill  doctor  emergency        1

In [10]:
staff.head()

       staff_id       staff_name    role    service
0  STF-5ca26577     Allison Hill  doctor  emergency
1  STF-02ae59ca      Noah Rhodes  doctor  emergency
2  STF-d8006e7c  Angie Henderson  doctor  emergency
3  STF-212d8b31    Daniel Wagner  doctor  emergency
4  STF-107a58e4  Cristian Santos  doctor  emergency

In [12]:
print("patient:", patients.shape)
print("services:", services.shape)
print("staff:", staff.shape)
print("schedule:", schedule.shape)

patient: (1000, 7)
services: (208, 10)
staff: (110, 4)
schedule: (6552, 6)

In [13]:
patients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   patient_id      1000 non-null   object
 1   name            1000 non-null   object
 2   age             1000 non-null   int64
 3   arrival_date    1000 non-null   object
 4   departure_date  1000 non-null   object
 5   service         1000 non-null   object
 6   satisfaction    1000 non-null   int64
dtypes: int64(2), object(5)
memory usage: 54.8+ KB

In [14]:
services.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   week                  208 non-null    int64
 1   month                 208 non-null    int64
 2   service               208 non-null    object
 3   available_beds        208 non-null    int64
 4   patients_request      208 non-null    int64
 5   patients_admitted     208 non-null    int64
 6   patients_refused      208 non-null    int64
 7   patient_satisfaction  208 non-null    int64
 8   staff_morale          208 non-null    int64
 9   event                 208 non-null    object
dtypes: int64(8), object(2)
memory usage: 16.4+ KB

In [15]:
staff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110 entries, 0 to 109
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   staff_id    110 non-null    object
 1   staff_name  110 non-null    object
 2   role        110 non-null    object
 3   service     110 non-null    object
dtypes: object(4)
memory usage: 3.6+ KB

In [16]:
schedule.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6552 entries, 0 to 6551
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   week        6552 non-null   int64
 1   staff_id    6552 non-null   object
 2   staff_name  6552 non-null   object
 3   role        6552 non-null   object
 4   service     6552 non-null   object
 5   present     6552 non-null   int64
dtypes: int64(2), object(4)
memory usage: 307.3+ KB

In [17]:
patients.isnull().sum()

patient_id        0
name              0
age               0
arrival_date      0
departure_date    0
service           0
satisfaction      0
dtype: int64

In [18]:
services.isnull().sum()

week                    0
month                   0
service                 0
available_beds          0
patients_request        0
patients_admitted       0
patients_refused        0
patient_satisfaction    0
staff_morale            0
event                   0
dtype: int64

In [19]:
staff.isnull().sum()

staff_id      0
staff_name    0
role          0
service       0
dtype: int64

In [20]:
schedule.isnull().sum()

week          0
staff_id      0
staff_name    0
role          0
service       0
present       0
dtype: int64

In [21]:
print("Duplicate patients:", patients.duplicated().sum())
print("Duplicate services:", services.duplicated().sum())
print("Duplicate staff:", staff.duplicated().sum())
print("Duplicate schedule:", schedule.duplicated().sum())

Duplicate patients: 0
Duplicate services: 0
Duplicate staff: 0
Duplicate schedule: 0

In [22]:
def clean_column_names(df):
    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_")
    )
    return df

patients = clean_column_names(patients)
services = clean_column_names(services)
staff = clean_column_names(staff)
schedule = clean_column_names(schedule)

In [23]:
print("patients columns:", patients.columns.tolist())
print("services columns:", services.columns.tolist())
print("staff columns:", staff.columns.tolist())
print("schedule columns:", schedule.columns.tolist())

patients columns: ['patient_id', 'name', 'age', 'arrival_date', 'departure_date', 'service', 'satisfaction']
services columns: ['week', 'month', 'service', 'available_beds', 'patients_request', 'patients_admitted', 'patients_refused', 'patient_satisfaction', 'staff_morale', 'event']
staff columns: ['staff_id', 'staff_name', 'role', 'service']
schedule columns: ['week', 'staff_id', 'staff_name', 'role', 'service', 'present']

In [24]:
patients['arrival_date'] = pd.to_datetime(patients['arrival_date'])
patients['departure_date'] = pd.to_datetime(patients['departure_date'])

In [25]:
patients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   patient_id      1000 non-null   object
 1   name            1000 non-null   object
 2   age             1000 non-null   int64
 3   arrival_date    1000 non-null   datetime64[ns]
 4   departure_date  1000 non-null   datetime64[ns]
 5   service         1000 non-null   object
 6   satisfaction    1000 non-null   int64
dtypes: datetime64[ns](2), int64(2), object(3)
memory usage: 54.8+ KB

In [26]:
patients['length_of_stay'] = (
    patients['departure_date'] - patients['arrival_date']
).dt.days

In [27]:
patients['arrival_month'] = patients['arrival_date'].dt.month
patients['arrival_day_name'] = patients['arrival_date'].dt.day_name()

In [28]:
patients['length_of_stay'].describe()

count    1000.000000
mean        7.407000
std         3.953857
min         1.000000
25%         4.000000
50%         7.000000
75%        11.000000
max        14.000000
Name: length_of_stay, dtype: float64

In [29]:
patients[patients['length_of_stay'] < 0]

Empty DataFrame
Columns: [patient_id, name, age, arrival_date, departure_date, service, satisfaction, length_of_stay, arrival_month, arrival_day_name]
Index: []

In [30]:
patients = patients[patients['length_of_stay'] >= 0]

In [31]:
patients_by_service = patients.groupby('service').agg(
    total_patients=('patient_id', 'count'),
    avg_length_of_stay=('length_of_stay', 'mean'),
    avg_satisfaction=('satisfaction', 'mean')
).reset_index()

patients_by_service

            service  total_patients  avg_length_of_stay  avg_satisfaction
0               ICU             241            7.605809         79.921162
1         emergency             263            7.159696         79.547529
2  general_medicine             242            6.995868         78.574380
3           surgery             254            7.866142         80.314961

In [32]:
services.head()
services.columns.tolist()

['week',
 'month',
 'service',
 'available_beds',
 'patients_request',
 'patients_admitted',
 'patients_refused',
 'patient_satisfaction',
 'staff_morale',
 'event']

In [33]:
services['bed_utilization_rate'] = (
    services['patients_admitted'] / services['available_beds']
) * 100

services['refusal_rate'] = (
    services['patients_refused'] / services['patients_request']
) * 100

services['admission_rate'] = (
    services['patients_admitted'] / services['patients_request']
) * 100

In [34]:
services.replace([np.inf, -np.inf], np.nan, inplace=True)

services[['bed_utilization_rate', 'refusal_rate', 'admission_rate']] = (
    services[['bed_utilization_rate', 'refusal_rate', 'admission_rate']]
    .fillna(0)
)

In [35]:
service_pressure = services.groupby('service').agg(
    avg_available_beds=('available_beds', 'mean'),
    avg_requests=('patients_request', 'mean'),
    avg_admitted=('patients_admitted', 'mean'),
    avg_refused=('patients_refused', 'mean'),
    avg_bed_utilization=('bed_utilization_rate', 'mean'),
    avg_refusal_rate=('refusal_rate', 'mean'),
    avg_satisfaction=('patient_satisfaction', 'mean'),
    avg_staff_morale=('staff_morale', 'mean')
).reset_index()

service_pressure.sort_values('avg_refusal_rate', ascending=False)

,service,avg_available_beds,avg_requests,avg_admitted,avg_refused,avg_bed_utilization,avg_refusal_rate,avg_satisfaction,avg_staff_morale
1,emergency,22.788462,119.096154,22.788462,96.307692,100.000000,76.768903,77.884615,73.557692
2,general_medicine,46.230769,82.115385,44.846154,37.269231,97.313582,34.621146,81.230769,73.096154
3,surgery,37.519231,43.096154,32.423077,10.673077,88.186759,17.257776,79.269231,72.634615
0,ICU,14.846154,15.173077,12.461538,2.711538,84.381561,11.661473,81.615385,70.980769

In [36]:
event_impact = services.groupby('event').agg(
    avg_requests=('patients_request', 'mean'),
    avg_admitted=('patients_admitted', 'mean'),
    avg_refused=('patients_refused', 'mean'),
    avg_refusal_rate=('refusal_rate', 'mean'),
    avg_satisfaction=('patient_satisfaction', 'mean'),
    avg_staff_morale=('staff_morale', 'mean')
).reset_index()

event_impact.sort_values('avg_refusal_rate', ascending=False)

,event,avg_requests,avg_admitted,avg_refused,avg_refusal_rate,avg_satisfaction,avg_staff_morale
1,flu,161.263158,35.105263,126.157895,65.701831,78.736842,72.894737
0,donation,54.714286,25.571429,29.142857,38.990793,82.714286,80.142857
2,none,56.201220,27.823171,28.378049,31.887728,79.725610,73.146341
3,strike,40.545455,23.909091,16.636364,24.753656,82.818182,53.727273

In [37]:
staff_by_service = staff.groupby(['service', 'role']).agg(
    staff_count=('staff_id', 'count')
).reset_index()

staff_by_service

             service               role  staff_count
0                ICU             doctor            6
1                ICU              nurse           18
2                ICU  nursing_assistant            8
3          emergency             doctor            5
4          emergency              nurse           19
5          emergency  nursing_assistant            5
6   general_medicine             doctor            3
7   general_medicine              nurse           19
8   general_medicine  nursing_assistant            5
9            surgery             doctor            4
10           surgery              nurse           13
11           surgery  nursing_assistant            5

In [38]:
schedule.head()
schedule['present'].value_counts()

present
1    3930
0    2622
Name: count, dtype: int64

In [39]:
schedule_summary = schedule.groupby(['week', 'service']).agg(
    scheduled_staff=('staff_id', 'count'),
    present_staff=('present', 'sum')
).reset_index()

schedule_summary['absent_staff'] = (
    schedule_summary['scheduled_staff'] - schedule_summary['present_staff']
)

schedule_summary['absence_rate'] = (
    schedule_summary['absent_staff'] / schedule_summary['scheduled_staff']
) * 100

schedule_summary.head()

,week,service,scheduled_staff,present_staff,absent_staff,absence_rate
0,1,ICU,34,31,3,8.823529
1,1,emergency,39,35,4,10.256410
2,1,general_medicine,28,27,1,3.571429
3,1,surgery,25,23,2,8.000000
4,2,ICU,34,30,4,11.764706

In [40]:
operations = services.merge(
    schedule_summary,
    on=['week', 'service'],
    how='left'
)

operations.head()

,week,month,service,available_beds,patients_request,patients_admitted,patients_refused,patient_satisfaction,staff_morale,event,bed_utilization_rate,refusal_rate,admission_rate,scheduled_staff,present_staff,absent_staff,absence_rate
0,1,1,emergency,32,76,32,44,67,70,none,100.0,57.894737,42.105263,39,35,4,10.256410
1,1,1,surgery,45,130,45,85,83,78,flu,100.0,65.384615,34.615385,25,23,2,8.000000
2,1,1,general_medicine,37,201,37,164,97,43,flu,100.0,81.592040,18.407960,28,27,1,3.571429
3,1,1,ICU,22,31,22,9,84,91,flu,100.0,29.032258,70.967742,34,31,3,8.823529
4,2,1,emergency,28,169,28,141,75,64,none,100.0,83.431953,16.568047,39,37,2,5.128205

In [41]:
operations['patients_per_present_staff'] = (
    operations['patients_admitted'] / operations['present_staff']
)

operations['requests_per_present_staff'] = (
    operations['patients_request'] / operations['present_staff']
)

operations.replace([np.inf, -np.inf], np.nan, inplace=True)
operations[['patients_per_present_staff', 'requests_per_present_staff']] = (
    operations[['patients_per_present_staff', 'requests_per_present_staff']]
    .fillna(0)
)

In [47]:
absence_correlation = operations[[
    'absence_rate',
    'patients_per_present_staff',
    'requests_per_present_staff'
]].corr()

absence_correlation

,absence_rate,patients_per_present_staff,requests_per_present_staff
absence_rate,1.000000,-0.653513,-0.564390
patients_per_present_staff,-0.653513,1.000000,0.630117
requests_per_present_staff,-0.564390,0.630117,1.000000

In [48]:
absence_correlation.to_csv("absence_pressure_correlation.csv")

In [49]:
from google.colab import files

files.download("absence_pressure_correlation.csv")

In [50]:
department_summary = operations.groupby('service').agg(
    avg_absence_rate=('absence_rate', 'mean'),
    avg_refusal_rate=('refusal_rate', 'mean'),
    avg_patients_per_staff=('patients_per_present_staff', 'mean'),
    avg_satisfaction=('patient_satisfaction', 'mean'),
    avg_morale=('staff_morale', 'mean')
).reset_index().sort_values('avg_refusal_rate', ascending=False)

department_summary

,service,avg_absence_rate,avg_refusal_rate,avg_patients_per_staff,avg_satisfaction,avg_morale
1,emergency,39.595661,76.768903,0.427968,77.884615,73.557692
2,general_medicine,41.002747,34.621146,1.206610,81.230769,73.096154
3,surgery,39.769231,17.257776,1.003351,79.269231,72.634615
0,ICU,39.875566,11.661473,0.286121,81.615385,70.980769

In [51]:
department_summary.to_csv("department_summary.csv", index=False)

In [52]:
from google.colab import files

files.download("department_summary.csv")

In [45]:
patients.to_csv("patients_cleaned.csv", index=False)
services.to_csv("services_weekly_cleaned.csv", index=False)
schedule_summary.to_csv("staff_schedule_summary.csv", index=False)
operations.to_csv("hospital_operations_cleaned.csv", index=False)
staff_by_service.to_csv("staff_by_service.csv", index=False)

In [46]:
from google.colab import files

files.download("patients_cleaned.csv")
files.download("services_weekly_cleaned.csv")
files.download("staff_schedule_summary.csv")
files.download("hospital_operations_cleaned.csv")
files.download("staff_by_service.csv")

In [53]:
patients_by_service.to_csv("patients_by_service.csv", index=False)

service_pressure.to_csv("service_pressure_summary.csv", index=False)

event_impact.to_csv("event_impact_analysis.csv", index=False)

from google.colab import files

files.download("patients_by_service.csv")
files.download("service_pressure_summary.csv")
files.download("event_impact_analysis.csv")